version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - 5432:5432

  server:
    restart: on-failure
    build: ./
    expose:
      - ${API_SERVER_PORT}
    environment:
      PG_CONNECTION_STRING: 'postgresql://postgres:postgres@db/notifications'
      NODE_ENV: ${NODE_ENV}
      REACT_APP_PORT: ${REACT_APP_PORT}
      API_SERVER_PORT: ${API_SERVER_PORT}
      NGINX_PORT: ß${NGINX_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    volumes:
      - ./:/usr/app/notifications-ui-server
    depends_on:
      - db
    links:
      - db

  client:
    restart: on-failure
    container_name: client
    build: ./client
    expose:
      - ${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./client/src:/usr/app/notifications-ui-client/src
    depends_on:
      - server
    links:
      - server
